[package]

## Rust configuration
edition = "2018"
target = ["bin"]
publish = false # never publish this utility

## Project Definition
name = "story-line-counter"
version = "0.1.0"

## Project Metadata
keywords = ["git", "version1", "jira"]
categories = ["command-line-utilities"]
authors = ["Lea Fairbanks <lfairbanks@mastercontrol.com>"]

## Repository information
repository = "https://github.com/leamc/story-line-counter"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "~0.9"
regex = "~1.2"
serde = { version = "~1.0", features = ["derive"] }
clap = {version = "~2.33", features = ["yaml"]}
