[package]

## Rust configuration
edition = "2018"
publish = false # never publish this utility

## Project Definition
name = "story-line-counter"
version = "0.1.0"

## Project Metadata
keywords = ["mastercontrol", "git", "version1"]
categories = ["command-line-utilities"]
authors = ["Lea Fairbanks <lfairbanks@mastercontrol.com>"]

## Repository information
repository = "https://github.com/leamc/story-line-counter"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.9.2"
